services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: aero
      POSTGRES_PASSWORD: aero
      POSTGRES_DB: aero
    ports:
      - '5433:5432'
    volumes:
      - aero_pg:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U aero']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6381:6379'
    volumes:
      - aero_redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27018:27017'
    volumes:
      - aero_mongo:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  aero_pg:
  aero_redis:
  aero_mongo:
